#org.gradle.java.home=/Users/kibahaonline/.sdkman/candidates/java/current
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
